export type ChannelRow = {
	id: string;
	name: string;
	base_url: string;
	api_key: string;
	weight: number;
	status: string;
	rate_limit?: number | null;
	models_json?: string | null;
	type?: number | null;
	group_name?: string | null;
	priority?: number | null;
	metadata_json?: string | null;
	test_time?: number | string | null;
	response_time_ms?: number | null;
	system_token?: string | null;
	system_userid?: string | null;
	checkin_enabled?: number | boolean | null;
	checkin_url?: string | null;
	last_checkin_date?: string | null;
	last_checkin_status?: string | null;
	last_checkin_message?: string | null;
	last_checkin_at?: string | null;
	auto_disable_hit_count?: number | null;
	auto_disabled_until?: number | null;
	auto_disabled_reason_code?: string | null;
	auto_disabled_permanent?: number | null;
	created_at?: string | null;
	updated_at?: string | null;
};

export type ChannelRecord = ChannelRow;
